apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  labels:
    app: nginx

spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: apache
        image: nginx
        ports:
        - containerPort: 80

